version: '3.8'

services:
  postgres-base: &postgres-base
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres-network

  postgres1:
    <<: *postgres-base
    volumes:
      - postgres1-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_1}:5432

  postgres2:
    <<: *postgres-base
    volumes:
      - postgres2-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_2}:5432

  postgres3:
    <<: *postgres-base
    volumes:
      - postgres3-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_3}:5432

volumes:
  postgres1-data:
  postgres2-data:
  postgres3-data:

networks:
  postgres-network:
